services:
  redis:
    image: redis:7-alpine
    container_name: redis-nik
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: mongo-redis-nik
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: redis-nik
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data: